services:
  - type: web
    name: ciau-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ciau_admin.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ciau_admin.settings
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"