# Generated by Django 4.2.8 on 2025-04-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediafile_title_alter_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='portfolio_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.portfolioproject'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='Missions CIAU'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='objectifs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom du Maître d'Ouvrage"),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='project_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="État d'avancement"),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='surface_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surface utile'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année'),
        ),
    ]
