# Generated by Django 4.2.8 on 2025-04-17 18:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediafile_portfolio_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='approach',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='mission',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Missions CIAU'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='objectifs',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
